# Generated by Django 3.2.22 on 2023-10-30 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nombre')),
                ('isbn', models.IntegerField(default=0, verbose_name='ISBN')),
                ('publisher_date', models.DateField()),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
