# Generated by Django 3.2.22 on 2023-10-31 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
    ]
